version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"

submodules:
  include: all
  recursive: true

sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt
