[project]
name = "ngff-anatomical-orientation"
version = "0.2.0"
description = "Build the model, schema, language bindings for the NGFF axis anatomical orientation proposal"
authors = ["Matt McCormick <matt@fideus.io>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
gen-markdown = "gen-markdown -d ./markdown ./orientation.yml"
gen-json-schema = "gen-json-schema orientation.yml > orientation.schema.json"
gen-pydantic = "gen-pydantic orientation.yml > orientation.py"
gen-typescript = "gen-typescript orientation.yml > orientation.ts"
gen-all = { depends-on = ["gen-markdown", "gen-json-schema", "gen-pydantic", "gen-typescript" ] }

[dependencies]
python = ">=3.12.4,<4"

[pypi-dependencies]
linkml = ">=1.9.2, <2"
