name: Request Reviewers
on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  request:
    # Skip PRs labeled 'infra' and PRs opened by bots
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'infra') && !endsWith(github.event.pull_request.user.login, '[bot]') }}
    runs-on: ubuntu-latest
    name: Request Reviewers
    steps:
      - uses: necojackarc/auto-request-review@9a4b11888f2d60c79120c5413f13eb63febc2b68 # v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/reviewers.yml
